# Generated by Django 5.1.7 on 2025-03-21 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_remove_book_genre_remove_book_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
